version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: skilldb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://user:password@mongo:27017/$skilldb?authSource=admin
      SPRING_REDIS_HOST: redis

volumes:
  mongo_data:
    driver: local
