version: '3.8'
services:
  postgress:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skilldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"


volumes:
  postgres_data:
    driver: local
