version: '3.8'
services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skilldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
  jaeger:
    image: jaegertracing/all-in-one:latest # Obraz zawiera kolektor, agenta, zapytania i UI
    container_name: jaeger
    ports:
      - "6831:6831/udp"  # Agent Jaeger (dla starszych klientów Jaeger)
      - "16686:16686"    # Interfejs użytkownika Jaeger
      - "4317:4317"      # Kolektor OTLP gRPC
      - "4318:4318"      # Kolektor OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true # Włącz odbieranie danych OTLP


volumes:
  postgres_data:
    driver: local
