spring:
  application:
    name: skill
  datasource:
    url: jdbc:postgresql://localhost:5432/skilldb
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  flyway:
    locations: classpath:db/changelog/postgres

logging:
  pattern:
    correlation: "[ %X{trace_id:-},%X{span_id:-} ] "
  level:
    com.project.skill: debug

otel:
  service:
    name: moja-usluga-otel
  exporter:
    otlp:
      endpoint: http://localhost:4318
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  propagators: tracecontext,baggage
  resource:
    attributes:
      environment: staging
      custom.attribute: wartosc_atrybutu