spring:
  application:
    name: skill
  datasource:
    url: jdbc:postgresql://localhost:5432/skilldb
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  flyway:
    locations: classpath:db/changelog/postgres

logging:
  level:
    com.project.skill: debug