spring:
  application:
    name: skill
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
    mongodb:
      uri: mongodb://${MONGO_USER:user}:${MONGO_PASSWORD:password}@localhost:27017/${MONGO_DATABASE:skilldb}?authSource=admin

logging:
  level:
    com.project.skill: debug