spring:
  application:
    name: skill
  datasource:
    url: jdbc:postgresql://localhost:5432/skilldb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    locations: classpath:db/changelog/postgres

logging:
  level:
    com.project.skill: debug